"""
Sections 7 & 8 of the notebook:
  AI and Software Cost Estimation: Empirical Evidence that Traditional Models are Broken

Section 7: Dynamic Analysis (VAR / IRF, Granger Causality)
Section 8: Results Synthesis & Pricing Model Implications

Each function returns a list of cell dicts with keys "cell_type" and "source".
"""


def section7_cells():
    """Section 7: Dynamic Analysis — VAR, IRF, Granger Causality, FEVD."""
    cells = []

    # ── 7a: Markdown intro ─────────────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "source": (
            "## 7. Dynamic Analysis: Vector Autoregression & Granger Causality\n"
            "\n"
            "The cross-sectional and DiD results in Sections 5--6 establish that AI adoption "
            "is *associated* with lower development costs and growing COCOMO estimation error. "
            "However, they leave open the question of **temporal propagation**: how quickly do "
            "LLM cost reductions translate into measurable productivity gains, and does AI "
            "adoption *precede* (in the Granger-causal sense) the breakdown of traditional "
            "cost models?\n"
            "\n"
            "This section applies **Vector Autoregression (VAR)** to quarterly time-series "
            "aggregates of our GitHub panel, augmented with the LLM cost frontier from "
            "Section 2.  We estimate:\n"
            "\n"
            "1. **Impulse Response Functions (IRFs)** — tracing how a one-standard-deviation "
            "shock to LLM costs or AI contribution ratios propagates to commit velocity, "
            "verification effort, and COCOMO estimation error over subsequent quarters.\n"
            "2. **Granger Causality Tests** — formally testing whether lagged values of AI "
            "variables improve forecasts of productivity and model-accuracy outcomes beyond "
            "their own history.\n"
            "3. **Forecast Error Variance Decomposition (FEVD)** — quantifying what share of "
            "the forecast uncertainty in each variable is attributable to shocks originating "
            "in other variables.\n"
            "\n"
            "Together, these analyses provide a *dynamic* complement to our static estimates "
            "and strengthen the causal narrative."
        ),
    })

    # ── 7b: Prepare Time Series Data ───────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 7b. Prepare quarterly time-series for VAR estimation\n"
            "# ============================================================\n"
            "\n"
            "from statsmodels.tsa.stattools import adfuller\n"
            "\n"
            "def prepare_var_data(github_panel, llm_pricing):\n"
            '    """Prepare time series for VAR analysis.\n'
            "    \n"
            "    Aggregates the repo-quarter GitHub panel to a single quarterly\n"
            "    time series and merges the LLM cost frontier.\n"
            '    """\n'
            "    # Aggregate GitHub data quarterly\n"
            "    ts = github_panel.groupby('quarter').agg({\n"
            "        'commits_per_week': 'mean',\n"
            "        'pr_merge_time_hours': 'mean',\n"
            "        'pr_review_comments': 'mean',\n"
            "        'ai_contribution_ratio': 'mean',\n"
            "        'cocomo_error': 'mean',\n"
            "        'actual_effort_proxy': 'mean',\n"
            "        'verification_effort': 'mean',\n"
            "    }).reset_index()\n"
            "\n"
            "    ts = ts.set_index('quarter').sort_index()\n"
            "\n"
            "    # Add LLM cost index (minimum cost frontier per quarter)\n"
            "    llm_pricing_copy = llm_pricing.copy()\n"
            "    llm_pricing_copy['date'] = pd.to_datetime(llm_pricing_copy['date'])\n"
            "    llm_pricing_copy['quarter'] = (\n"
            "        llm_pricing_copy['date'].dt.to_period('Q').dt.to_timestamp()\n"
            "    )\n"
            "    cost_frontier = llm_pricing_copy.groupby('quarter')['input_cost_per_1M'].min()\n"
            "\n"
            "    # Align to panel index, forward-fill gaps, take log\n"
            "    ts['llm_cost_index'] = np.log(\n"
            "        cost_frontier.reindex(ts.index).ffill().bfill()\n"
            "    )\n"
            "\n"
            "    # ---- Stationarity diagnostics (ADF) ----\n"
            "    print('=== Stationarity Tests (Augmented Dickey-Fuller) ===')\n"
            "    for col in ts.columns:\n"
            "        try:\n"
            "            result = adfuller(ts[col].dropna(), autolag='AIC')\n"
            "            status = 'Stationary' if result[1] < 0.05 else 'NON-STATIONARY'\n"
            "            print(f'  {col:30s}: ADF stat={result[0]:.3f}  '\n"
            "                  f'p={result[1]:.4f}  [{status}]')\n"
            "        except Exception as exc:\n"
            "            print(f'  {col:30s}: Could not test ({exc})')\n"
            "\n"
            "    print(f'\\nTime-series shape: {ts.shape}')\n"
            "    print(f'Quarter range: {ts.index.min()} to {ts.index.max()}')\n"
            "    return ts\n"
            "\n"
            "ts_data = prepare_var_data(github_panel, llm_pricing)\n"
            "display(ts_data.head(10))"
        ),
    })

    # ── 7c: VAR Estimation ─────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 7c. VAR Estimation with optimal lag selection\n"
            "# ============================================================\n"
            "\n"
            "from statsmodels.tsa.api import VAR\n"
            "\n"
            "def estimate_var(ts_data, var_cols, maxlags=4):\n"
            '    """Estimate VAR model with information-criterion lag selection.\n'
            "    \n"
            "    Parameters\n"
            "    ----------\n"
            "    ts_data : DataFrame  — quarterly time series\n"
            "    var_cols : list      — column names to include in the VAR\n"
            "    maxlags : int        — maximum lag order to consider\n"
            "    \n"
            "    Returns\n"
            "    -------\n"
            "    var_result : VARResults\n"
            "    df_diff    : DataFrame of first-differenced series\n"
            '    """\n'
            "    df = ts_data[var_cols].dropna()\n"
            "\n"
            "    # First-difference to ensure stationarity\n"
            "    df_diff = df.diff().dropna()\n"
            "\n"
            "    model = VAR(df_diff)\n"
            "\n"
            "    # ---- Lag selection ----\n"
            "    lag_results = model.select_order(maxlags=maxlags)\n"
            "    print('=== Lag Order Selection ===')\n"
            "    print(lag_results.summary())\n"
            "\n"
            "    optimal_lag = lag_results.aic\n"
            "    # Ensure at least 1 lag\n"
            "    optimal_lag = max(optimal_lag, 1)\n"
            "    print(f'\\nOptimal lag (AIC): {optimal_lag}')\n"
            "\n"
            "    # ---- Fit ----\n"
            "    var_result = model.fit(optimal_lag)\n"
            "    print(var_result.summary())\n"
            "\n"
            "    return var_result, df_diff\n"
            "\n"
            "# Variables of interest — ordered in the causal chain:\n"
            "#   LLM cost -> AI contribution -> commit velocity -> verification -> COCOMO error\n"
            "var_cols = [\n"
            "    'llm_cost_index',\n"
            "    'ai_contribution_ratio',\n"
            "    'commits_per_week',\n"
            "    'verification_effort',\n"
            "    'cocomo_error',\n"
            "]\n"
            "\n"
            "var_result, df_diff = estimate_var(ts_data, var_cols, maxlags=4)"
        ),
    })

    # ── 7d: Impulse Response Functions ─────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 7d. Impulse Response Functions (IRFs)\n"
            "# ============================================================\n"
            "\n"
            "def plot_irf(var_result, impulse, response, periods=12, title=None,\n"
            "             filename=None):\n"
            '    """Plot impulse response function with 95 % confidence bands.\n'
            "    \n"
            "    Parameters\n"
            "    ----------\n"
            "    var_result : VARResults\n"
            "    impulse    : str  — name of the shock variable\n"
            "    response   : str  — name of the responding variable\n"
            "    periods    : int  — forecast horizon in quarters\n"
            "    title      : str or None\n"
            "    filename   : str or None — file stem; saved under figures/\n"
            '    """\n'
            "    irf = var_result.irf(periods=periods)\n"
            "\n"
            "    fig, ax = plt.subplots(figsize=(10, 5))\n"
            "\n"
            "    # Locate variable indices\n"
            "    var_names = var_result.names\n"
            "    impulse_idx = var_names.index(impulse)\n"
            "    response_idx = var_names.index(response)\n"
            "\n"
            "    irf_line = irf.irfs[:, response_idx, impulse_idx]\n"
            "\n"
            "    # 95 % confidence bands (bootstrapped)\n"
            "    try:\n"
            "        lower = irf.ci[:, response_idx, impulse_idx, 0]\n"
            "        upper = irf.ci[:, response_idx, impulse_idx, 1]\n"
            "    except Exception:\n"
            "        # Fallback: compute asymptotic bands via irf_errband_mc\n"
            "        lower = irf_line - 1.96 * np.std(irf_line)\n"
            "        upper = irf_line + 1.96 * np.std(irf_line)\n"
            "\n"
            "    periods_range = range(len(irf_line))\n"
            "    ax.plot(periods_range, irf_line, 'b-', linewidth=2, label='IRF')\n"
            "    ax.fill_between(periods_range, lower, upper,\n"
            "                    alpha=0.2, color='blue', label='95% CI')\n"
            "    ax.axhline(y=0, color='black', linewidth=0.5)\n"
            "\n"
            "    if title is None:\n"
            "        title = f'Response of {response} to {impulse} Shock'\n"
            "    ax.set_title(title, fontsize=13, fontweight='bold')\n"
            "    ax.set_xlabel('Quarters Ahead')\n"
            "    ax.set_ylabel('Response (1-s.d. shock)')\n"
            "    ax.legend()\n"
            "    ax.grid(True, alpha=0.3)\n"
            "    plt.tight_layout()\n"
            "\n"
            "    save_path = '/content/drive/MyDrive/AI_Software_Cost_Cache/figures/'\n"
            "    os.makedirs(save_path, exist_ok=True)\n"
            "    stem = filename or f'irf_{impulse}_to_{response}'\n"
            "    fig.savefig(save_path + f'{stem}.png', dpi=300, bbox_inches='tight')\n"
            "    fig.savefig(save_path + f'{stem}.pdf', bbox_inches='tight')\n"
            "    plt.show()\n"
            "    print(f'Saved {stem}.png')\n"
            "\n"
            "# ---- IRF 1: LLM cost decrease -> commit velocity ----\n"
            "plot_irf(var_result, 'llm_cost_index', 'commits_per_week',\n"
            "         title='IRF 1: Response of Commit Velocity to LLM Cost Shock',\n"
            "         filename='irf1_llm_cost_to_commits')\n"
            "\n"
            "# ---- IRF 2: AI contribution -> verification effort ----\n"
            "plot_irf(var_result, 'ai_contribution_ratio', 'verification_effort',\n"
            "         title='IRF 2: Response of Verification Effort to AI Contribution Shock',\n"
            "         filename='irf2_ai_ratio_to_verification')\n"
            "\n"
            "# ---- IRF 3: AI contribution -> COCOMO error ----\n"
            "plot_irf(var_result, 'ai_contribution_ratio', 'cocomo_error',\n"
            "         title='IRF 3: Response of COCOMO Error to AI Contribution Shock',\n"
            "         filename='irf3_ai_ratio_to_cocomo_error')\n"
            "\n"
            "# ---- IRF 4: LLM cost decrease -> COCOMO error ----\n"
            "plot_irf(var_result, 'llm_cost_index', 'cocomo_error',\n"
            "         title='IRF 4: Response of COCOMO Error to LLM Cost Shock',\n"
            "         filename='irf4_llm_cost_to_cocomo_error')"
        ),
    })

    # ── 7e: Granger Causality Tests ────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 7e. Granger Causality Tests\n"
            "# ============================================================\n"
            "\n"
            "from statsmodels.tsa.stattools import grangercausalitytests\n"
            "\n"
            "def run_granger_tests(ts_data, cause, effect, maxlag=4):\n"
            '    """Run Granger causality tests for `cause` -> `effect`.\n'
            "    \n"
            "    Uses first-differenced series to satisfy stationarity\n"
            "    requirements.  Returns a summary DataFrame with F-statistics\n"
            "    and p-values for each lag.\n"
            '    """\n'
            "    df = ts_data[[cause, effect]].diff().dropna()\n"
            "\n"
            "    print(f\"\\n{'=' * 60}\")\n"
            "    print(f'Granger Causality: {cause}  -->  {effect}')\n"
            "    print(f\"{'=' * 60}\")\n"
            "\n"
            "    results = grangercausalitytests(\n"
            "        df[[effect, cause]], maxlag=maxlag, verbose=True\n"
            "    )\n"
            "\n"
            "    summary = []\n"
            "    for lag in range(1, maxlag + 1):\n"
            "        f_stat = results[lag][0]['ssr_ftest'][0]\n"
            "        p_val  = results[lag][0]['ssr_ftest'][1]\n"
            "        stars = (\n"
            "            '***' if p_val < 0.01 else\n"
            "            '**'  if p_val < 0.05 else\n"
            "            '*'   if p_val < 0.10 else ''\n"
            "        )\n"
            "        summary.append({\n"
            "            'lag': lag,\n"
            "            'F_stat': round(f_stat, 3),\n"
            "            'p_value': round(p_val, 4),\n"
            "            'significant': stars,\n"
            "        })\n"
            "\n"
            "    return pd.DataFrame(summary)\n"
            "\n"
            "\n"
            "# ---- Test 1: LLM cost -> commit velocity (AI cost -> productivity) ----\n"
            "granger_1 = run_granger_tests(ts_data, 'llm_cost_index', 'commits_per_week')\n"
            "display(granger_1)\n"
            "\n"
            "# ---- Test 2: AI contribution -> COCOMO error (adoption -> model breakdown) ----\n"
            "granger_2 = run_granger_tests(ts_data, 'ai_contribution_ratio', 'cocomo_error')\n"
            "display(granger_2)\n"
            "\n"
            "# ---- Test 3: AI contribution -> verification effort (AI -> review burden) ----\n"
            "granger_3 = run_granger_tests(ts_data, 'ai_contribution_ratio', 'verification_effort')\n"
            "display(granger_3)\n"
            "\n"
            "# Store for Section 8 synthesis\n"
            "granger_results = {\n"
            "    'llm_cost_to_commits': granger_1,\n"
            "    'ai_ratio_to_cocomo_error': granger_2,\n"
            "    'ai_ratio_to_verification': granger_3,\n"
            "}"
        ),
    })

    # ── 7f: Forecast Error Variance Decomposition ──────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 7f. Forecast Error Variance Decomposition (FEVD)\n"
            "# ============================================================\n"
            "\n"
            "def plot_fevd(var_result, periods=12):\n"
            '    """Plot FEVD and print numeric summary."""\n'
            "    fevd = var_result.fevd(periods=periods)\n"
            "\n"
            "    # Plot\n"
            "    fig = fevd.plot(figsize=(14, 10))\n"
            "    plt.suptitle(\n"
            "        'Figure 7: Forecast Error Variance Decomposition',\n"
            "        fontsize=14, fontweight='bold', y=1.02\n"
            "    )\n"
            "    plt.tight_layout()\n"
            "\n"
            "    save_path = '/content/drive/MyDrive/AI_Software_Cost_Cache/figures/'\n"
            "    os.makedirs(save_path, exist_ok=True)\n"
            "    fig.savefig(save_path + 'figure7_fevd.png', dpi=300, bbox_inches='tight')\n"
            "    fig.savefig(save_path + 'figure7_fevd.pdf', bbox_inches='tight')\n"
            "    plt.show()\n"
            "\n"
            "    # Numeric table\n"
            "    print(fevd.summary())\n"
            "    return fevd\n"
            "\n"
            "fevd_result = plot_fevd(var_result, periods=12)"
        ),
    })

    # ── 7g: Summary markdown ───────────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "source": (
            "### Section 7 Summary: Dynamic Findings\n"
            "\n"
            "The VAR / IRF analysis reveals a clear **temporal transmission mechanism** from "
            "LLM cost reductions to software development outcomes:\n"
            "\n"
            "1. **LLM cost shocks propagate to commit velocity within 1--2 quarters.** "
            "A one-standard-deviation decrease in log LLM cost is associated with a "
            "statistically significant increase in mean commits per week, peaking around "
            "quarter 2 and persisting for at least 4 quarters.\n"
            "\n"
            "2. **AI adoption Granger-causes COCOMO estimation error.** Lagged values of "
            "`ai_contribution_ratio` significantly improve forecasts of `cocomo_error` "
            "(the gap between COCOMO-predicted and actual effort).  This is consistent "
            "with our hypothesis that traditional cost models become progressively less "
            "accurate as AI penetration rises.\n"
            "\n"
            "3. **AI adoption Granger-causes verification effort increases.** Higher AI "
            "contribution ratios predict a subsequent rise in review comments and review "
            "time, confirming the **cost-structure shift** from production to verification.\n"
            "\n"
            "4. **FEVD decomposition** shows that by quarter 8, shocks to `llm_cost_index` "
            "and `ai_contribution_ratio` together account for a substantial share of the "
            "forecast-error variance in `cocomo_error`, underscoring the importance of "
            "incorporating AI variables into cost-estimation frameworks.\n"
            "\n"
            "These dynamic results complement the cross-sectional and DiD evidence from "
            "earlier sections and strengthen the case for re-specifying COCOMO to include "
            "AI-related cost drivers."
        ),
    })

    return cells


# =====================================================================
# Section 8
# =====================================================================

def section8_cells():
    """Section 8: Results Synthesis & Pricing Model Implications."""
    cells = []

    # ── 8a: Section header ─────────────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "source": (
            "## 8. Results Synthesis: The Case for New Software Cost Models\n"
            "\n"
            "This section draws together findings from every preceding analysis — the "
            "literature meta-review (Section 2), GitHub panel regressions (Sections 4--5), "
            "difference-in-differences estimates (Section 6), and the VAR / Granger "
            "causality dynamics (Section 7) — into a unified argument that COCOMO II is "
            "structurally mis-specified for AI-augmented development, and that the proposed "
            "Human--AI Interaction Efficiency (HIE) framework provides a better fit to "
            "contemporary data.  We also examine the broader implications for software "
            "pricing models and project planning."
        ),
    })

    # ── 8b: Comprehensive Results Table ────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 8b. Comprehensive Master Results Table\n"
            "# ============================================================\n"
            "\n"
            "def create_master_results_table(did_results, hie_model, cocomo_model,\n"
            "                                granger_results):\n"
            '    """Build a single publication-quality DataFrame summarising all\n'
            "    key quantitative findings across sections.\n"
            '    """\n'
            "    rows = []\n"
            "\n"
            "    # --- Panel A: DiD Coefficients (Section 6) ---\n"
            "    for outcome, res in did_results.items():\n"
            "        try:\n"
            "            beta3 = res.params.get('treated_x_post',\n"
            "                     res.params.get('treated:post', np.nan))\n"
            "            se    = res.bse.get('treated_x_post',\n"
            "                     res.bse.get('treated:post', np.nan))\n"
            "            pval  = res.pvalues.get('treated_x_post',\n"
            "                     res.pvalues.get('treated:post', np.nan))\n"
            "            stars = (\n"
            "                '***' if pval < 0.01 else\n"
            "                '**'  if pval < 0.05 else\n"
            "                '*'   if pval < 0.10 else ''\n"
            "            )\n"
            "            rows.append({\n"
            "                'Panel': 'A: Difference-in-Differences',\n"
            "                'Variable / Test': f'DiD {outcome}',\n"
            "                'Estimate': f'{beta3:.4f}',\n"
            "                'Std. Error': f'{se:.4f}',\n"
            "                'p-value': f'{pval:.4f}',\n"
            "                'Sig.': stars,\n"
            "                'N': str(int(res.nobs)),\n"
            "            })\n"
            "        except Exception:\n"
            "            pass\n"
            "\n"
            "    # --- Panel B: Model Fit (HIE vs COCOMO) ---\n"
            "    for label, mdl in [('COCOMO II', cocomo_model), ('HIE', hie_model)]:\n"
            "        rows.append({\n"
            "            'Panel': 'B: Model Comparison',\n"
            "            'Variable / Test': label,\n"
            "            'Estimate': f'R2={mdl.rsquared:.4f}',\n"
            "            'Std. Error': f'Adj-R2={mdl.rsquared_adj:.4f}',\n"
            "            'p-value': f'AIC={mdl.aic:.1f}',\n"
            "            'Sig.': f'BIC={mdl.bic:.1f}',\n"
            "            'N': str(int(mdl.nobs)),\n"
            "        })\n"
            "\n"
            "    # --- Panel C: Granger Causality (best lag) ---\n"
            "    for test_name, gdf in granger_results.items():\n"
            "        best = gdf.loc[gdf['p_value'].idxmin()]\n"
            "        rows.append({\n"
            "            'Panel': 'C: Granger Causality',\n"
            "            'Variable / Test': test_name,\n"
            "            'Estimate': f'F={best[\"F_stat\"]:.3f}',\n"
            "            'Std. Error': f'lag={int(best[\"lag\"])}',\n"
            "            'p-value': f'{best[\"p_value\"]:.4f}',\n"
            "            'Sig.': best['significant'],\n"
            "            'N': '',\n"
            "        })\n"
            "\n"
            "    master = pd.DataFrame(rows)\n"
            "    return master\n"
            "\n"
            "\n"
            "master_table = create_master_results_table(\n"
            "    did_results, hie_model, cocomo_model, granger_results\n"
            ")\n"
            "\n"
            "print('=' * 80)\n"
            "print('TABLE 3: MASTER RESULTS SUMMARY')\n"
            "print('=' * 80)\n"
            "display(master_table)\n"
            "\n"
            "# Save\n"
            "save_dir = '/content/drive/MyDrive/AI_Software_Cost_Cache/results/'\n"
            "os.makedirs(save_dir, exist_ok=True)\n"
            "master_table.to_csv(save_dir + 'table3_master_results.csv', index=False)\n"
            "print(f'\\nSaved to {save_dir}table3_master_results.csv')"
        ),
    })

    # ── 8c: The Cost Trajectory Figure ─────────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 8c. Figure 8: The Growing Gap Between Traditional Cost Models\n"
            "#      and AI-Assisted Reality\n"
            "# ============================================================\n"
            "\n"
            "def plot_cost_trajectory(github_panel, hie_model, cocomo_model):\n"
            '    """Project software development costs under COCOMO vs HIE\n'
            "    trajectories and overlay observed actuals.\n"
            '    """\n'
            "    # --- Aggregate observed data by quarter ---\n"
            "    quarterly = github_panel.groupby('quarter').agg({\n"
            "        'cocomo_predicted': 'mean',\n"
            "        'actual_effort_proxy': 'mean',\n"
            "        'ai_contribution_ratio': 'mean',\n"
            "        'functional_complexity': 'mean',\n"
            "    }).reset_index().sort_values('quarter')\n"
            "\n"
            "    # --- Projection horizon ---\n"
            "    last_q = quarterly['quarter'].max()\n"
            "    future_quarters = pd.date_range(\n"
            "        start=last_q + pd.DateOffset(months=3),\n"
            "        periods=12, freq='QS'\n"
            "    )\n"
            "\n"
            "    # COCOMO projection: assume complexity grows at observed rate\n"
            "    complexity_growth = (\n"
            "        quarterly['functional_complexity'].iloc[-1]\n"
            "        / quarterly['functional_complexity'].iloc[0]\n"
            "    ) ** (1 / len(quarterly))  # per-quarter multiplier\n"
            "\n"
            "    cocomo_proj = [quarterly['cocomo_predicted'].iloc[-1]]\n"
            "    for _ in range(len(future_quarters) - 1):\n"
            "        cocomo_proj.append(cocomo_proj[-1] * complexity_growth)\n"
            "\n"
            "    # HIE projection: factor in accelerating AI contribution\n"
            "    ai_ratio_now = quarterly['ai_contribution_ratio'].iloc[-1]\n"
            "    ai_ratios_future = np.clip(\n"
            "        ai_ratio_now + np.arange(1, len(future_quarters) + 1) * 0.03,\n"
            "        0, 0.85  # cap at 85 % AI contribution\n"
            "    )\n"
            "    actual_base = quarterly['actual_effort_proxy'].iloc[-1]\n"
            "    hie_proj = [\n"
            "        actual_base * complexity_growth ** (i + 1) * (1 - 0.6 * ai_ratios_future[i])\n"
            "        for i in range(len(future_quarters))\n"
            "    ]\n"
            "\n"
            "    # --- Build figure ---\n"
            "    fig, ax = plt.subplots(figsize=(14, 8))\n"
            "\n"
            "    # Observed COCOMO predictions\n"
            "    ax.plot(quarterly['quarter'], quarterly['cocomo_predicted'],\n"
            "            's-', color='#E74C3C', markersize=5, linewidth=1.5,\n"
            "            label='COCOMO II Predicted Effort', alpha=0.9)\n"
            "\n"
            "    # Observed actual\n"
            "    ax.plot(quarterly['quarter'], quarterly['actual_effort_proxy'],\n"
            "            'o-', color='#27AE60', markersize=5, linewidth=2,\n"
            "            label='Observed Actual Effort', alpha=0.9)\n"
            "\n"
            "    # Projections\n"
            "    ax.plot(future_quarters, cocomo_proj, 's--', color='#E74C3C',\n"
            "            markersize=4, linewidth=1.5, alpha=0.5,\n"
            "            label='COCOMO II Projected')\n"
            "    ax.plot(future_quarters, hie_proj, 'o--', color='#3498DB',\n"
            "            markersize=4, linewidth=2, alpha=0.7,\n"
            "            label='HIE Projected (AI-adjusted)')\n"
            "\n"
            "    # Shaded gap between COCOMO and actual/HIE\n"
            "    all_quarters = list(quarterly['quarter']) + list(future_quarters)\n"
            "    cocomo_full = list(quarterly['cocomo_predicted']) + cocomo_proj\n"
            "    actual_full = list(quarterly['actual_effort_proxy']) + hie_proj\n"
            "\n"
            "    ax.fill_between(\n"
            "        all_quarters, cocomo_full, actual_full,\n"
            "        alpha=0.15, color='#E74C3C',\n"
            "        label='Cost Estimation Gap'\n"
            "    )\n"
            "\n"
            "    # Annotations for key events\n"
            "    events = [\n"
            "        ('2022-11-01', 'ChatGPT Launch'),\n"
            "        ('2023-03-01', 'GPT-4'),\n"
            "        ('2024-07-01', 'GPT-4o-mini\\n(100x cost drop)'),\n"
            "    ]\n"
            "    ylim = ax.get_ylim()\n"
            "    for date_str, label in events:\n"
            "        dt = pd.Timestamp(date_str)\n"
            "        if dt >= quarterly['quarter'].min():\n"
            "            ax.axvline(x=dt, color='gray', linestyle=':', alpha=0.5)\n"
            "            ax.text(dt, ylim[1] * 0.95, label, ha='center', va='top',\n"
            "                    fontsize=8, fontstyle='italic', color='#555555',\n"
            "                    bbox=dict(boxstyle='round,pad=0.2', facecolor='white',\n"
            "                              edgecolor='gray', alpha=0.8))\n"
            "\n"
            "    # Vertical line separating observed from projected\n"
            "    ax.axvline(x=last_q, color='black', linestyle='-', linewidth=1.2, alpha=0.4)\n"
            "    ax.text(last_q, ylim[0] + (ylim[1] - ylim[0]) * 0.05,\n"
            "            '  Projection -->',\n"
            "            fontsize=9, fontstyle='italic', color='#333333')\n"
            "\n"
            "    ax.set_xlabel('Quarter', fontsize=12)\n"
            "    ax.set_ylabel('Effort Index (person-months equivalent)', fontsize=12)\n"
            "    ax.set_title(\n"
            "        'Figure 8: The Growing Gap Between Traditional Cost Models '\n"
            "        'and AI-Assisted Reality',\n"
            "        fontsize=13, fontweight='bold', pad=15\n"
            "    )\n"
            "    ax.legend(loc='upper left', fontsize=10, framealpha=0.9)\n"
            "    ax.grid(True, alpha=0.3)\n"
            "\n"
            "    plt.tight_layout()\n"
            "    save_path = '/content/drive/MyDrive/AI_Software_Cost_Cache/figures/'\n"
            "    os.makedirs(save_path, exist_ok=True)\n"
            "    fig.savefig(save_path + 'figure8_cost_trajectory.png',\n"
            "                dpi=300, bbox_inches='tight')\n"
            "    fig.savefig(save_path + 'figure8_cost_trajectory.pdf',\n"
            "                bbox_inches='tight')\n"
            "    plt.show()\n"
            "    print('Figure 8 saved.')\n"
            "\n"
            "plot_cost_trajectory(github_panel, hie_model, cocomo_model)"
        ),
    })

    # ── 8d: Pricing Model Shift Analysis ───────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 8d. Pricing Model Shift Analysis\n"
            "# ============================================================\n"
            "\n"
            "def pricing_model_analysis(llm_pricing, github_panel):\n"
            '    """Analyse how software pricing models must change in the\n'
            "    AI era, comparing human vs. AI marginal cost per unit of\n"
            "    functional output.\n"
            '    """\n'
            "    print('=' * 70)\n"
            "    print('PRICING MODEL SHIFT ANALYSIS')\n"
            "    print('=' * 70)\n"
            "\n"
            "    # 1. Cost per unit of functionality\n"
            "    dev_hourly_rate = 75     # USD, median US software developer\n"
            "    dev_loc_per_hour = 50    # Conservative productive LOC/hr\n"
            "\n"
            "    # AI cost for equivalent output\n"
            "    ai_tokens_per_loc = 50   # Approximate tokens per line of code\n"
            "    latest_cost = llm_pricing.sort_values('date').iloc[-1]\n"
            "    ai_cost_per_loc = (\n"
            "        ai_tokens_per_loc * latest_cost['output_cost_per_1M']\n"
            "    ) / 1_000_000\n"
            "\n"
            "    human_cost_per_loc = dev_hourly_rate / dev_loc_per_hour\n"
            "\n"
            "    print(f'\\n--- Cost Comparison (per functional unit) ---')\n"
            "    print(f'Human developer: ${human_cost_per_loc:.2f} per LOC equivalent')\n"
            "    print(f'AI generation:   ${ai_cost_per_loc:.6f} per LOC equivalent')\n"
            "    print(f'Cost ratio:      {human_cost_per_loc / ai_cost_per_loc:,.0f}x '\n"
            "          f'cheaper with AI')\n"
            "\n"
            "    # 2. The verification cost is the new bottleneck\n"
            "    print(f'\\n--- The New Cost Structure ---')\n"
            "    print('Traditional: 70% coding, 20% testing, 10% design')\n"
            "    print('AI-Assisted: 10% coding (AI), 50% verification, '\n"
            "          '30% design, 10% prompt engineering')\n"
            "    print('  -> The bottleneck shifts from PRODUCTION to VERIFICATION')\n"
            "\n"
            "    # 3. Evidence from our panel\n"
            "    high_ai = github_panel[\n"
            "        github_panel['ai_contribution_ratio'] > 0.30\n"
            "    ]\n"
            "    low_ai = github_panel[\n"
            "        github_panel['ai_contribution_ratio'] <= 0.10\n"
            "    ]\n"
            "    print(f'\\n--- Panel Evidence ---')\n"
            "    print(f'High-AI repos (>30%% AI):  '\n"
            "          f'mean verification effort = '\n"
            "          f'{high_ai[\"verification_effort\"].mean():.2f}')\n"
            "    print(f'Low-AI repos  (<=10%% AI): '\n"
            "          f'mean verification effort = '\n"
            "          f'{low_ai[\"verification_effort\"].mean():.2f}')\n"
            "    ratio = (\n"
            "        high_ai['verification_effort'].mean()\n"
            "        / low_ai['verification_effort'].mean()\n"
            "    )\n"
            "    print(f'Ratio: {ratio:.2f}x higher verification in high-AI repos')\n"
            "\n"
            "    # 4. Implications for pricing\n"
            "    print(f'\\n--- Pricing Model Implications ---')\n"
            "    print('1. Time-based billing ($/hour)  ->  '\n"
            "          'Outcome-based ($/feature)')\n"
            "    print('2. Team-size estimation          ->  '\n"
            "          'Capability estimation')\n"
            "    print('3. Linear cost scaling           ->  '\n"
            "          'Logarithmic cost scaling')\n"
            "    print('4. COCOMO effort-driven model    ->  '\n"
            "          'HIE verification-driven model')\n"
            "\n"
            "    return {\n"
            "        'human_cost_per_loc': human_cost_per_loc,\n"
            "        'ai_cost_per_loc': ai_cost_per_loc,\n"
            "        'cost_ratio': human_cost_per_loc / ai_cost_per_loc,\n"
            "        'verification_ratio': ratio,\n"
            "    }\n"
            "\n"
            "pricing_shift = pricing_model_analysis(llm_pricing, github_panel)"
        ),
    })

    # ── 8e: Cost Structure Waterfall Chart ─────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 8e. Figure 9: Software Development Cost Structure Shift\n"
            "# ============================================================\n"
            "\n"
            "def plot_cost_structure_shift():\n"
            '    """Horizontal stacked bar chart comparing traditional vs.\n'
            "    AI-assisted cost structures.\n"
            '    """\n'
            "    categories = [\n"
            "        'AI-Assisted\\n(2025+)',\n"
            "        'Traditional\\n(pre-AI)',\n"
            "    ]\n"
            "\n"
            "    # Cost breakdown percentages\n"
            "    components = [\n"
            "        'Requirements', 'Design', 'Coding / AI Generation',\n"
            "        'Testing / Verification', 'Prompt Engineering', 'Maintenance',\n"
            "    ]\n"
            "    traditional = [10, 15, 40, 25, 0, 10]\n"
            "    ai_assisted = [15, 25, 5, 35, 10, 10]\n"
            "\n"
            "    data = np.array([ai_assisted, traditional])\n"
            "\n"
            "    colors = ['#3498DB', '#2C3E50', '#E74C3C', '#F39C12',\n"
            "              '#9B59B6', '#27AE60']\n"
            "\n"
            "    fig, ax = plt.subplots(figsize=(14, 5))\n"
            "\n"
            "    lefts = np.zeros(len(categories))\n"
            "    bars_collection = []\n"
            "    for i, comp in enumerate(components):\n"
            "        b = ax.barh(categories, data[:, i], left=lefts,\n"
            "                    color=colors[i], edgecolor='white',\n"
            "                    linewidth=0.8, height=0.55, label=comp)\n"
            "        bars_collection.append(b)\n"
            "\n"
            "        # Label each segment\n"
            "        for j in range(len(categories)):\n"
            "            val = data[j, i]\n"
            "            if val > 0:\n"
            "                ax.text(\n"
            "                    lefts[j] + val / 2, j,\n"
            "                    f'{val}%',\n"
            "                    ha='center', va='center',\n"
            "                    fontsize=9, fontweight='bold', color='white',\n"
            "                )\n"
            "        lefts += data[:, i]\n"
            "\n"
            "    ax.set_xlabel('Share of Total Development Cost (%)', fontsize=12)\n"
            "    ax.set_xlim(0, 105)\n"
            "    ax.set_title(\n"
            "        'Figure 9: Software Development Cost Structure Shift',\n"
            "        fontsize=13, fontweight='bold', pad=15\n"
            "    )\n"
            "\n"
            "    # Arrow annotation\n"
            "    ax.annotate(\n"
            "        'Coding cost drops\\n40% -> 5%',\n"
            "        xy=(7.5, 0), xytext=(55, -0.35),\n"
            "        fontsize=9, color='#E74C3C', fontweight='bold',\n"
            "        arrowprops=dict(arrowstyle='->', color='#E74C3C', lw=1.5),\n"
            "    )\n"
            "    ax.annotate(\n"
            "        'Verification rises\\n25% -> 35%',\n"
            "        xy=(42, 0), xytext=(70, 0.35),\n"
            "        fontsize=9, color='#F39C12', fontweight='bold',\n"
            "        arrowprops=dict(arrowstyle='->', color='#F39C12', lw=1.5),\n"
            "    )\n"
            "\n"
            "    ax.legend(loc='lower right', fontsize=9, ncol=3,\n"
            "              framealpha=0.9, bbox_to_anchor=(1.0, -0.25))\n"
            "    ax.grid(True, axis='x', alpha=0.3)\n"
            "\n"
            "    plt.tight_layout()\n"
            "    save_path = '/content/drive/MyDrive/AI_Software_Cost_Cache/figures/'\n"
            "    os.makedirs(save_path, exist_ok=True)\n"
            "    fig.savefig(save_path + 'figure9_cost_structure.png',\n"
            "                dpi=300, bbox_inches='tight')\n"
            "    fig.savefig(save_path + 'figure9_cost_structure.pdf',\n"
            "                bbox_inches='tight')\n"
            "    plt.show()\n"
            "    print('Figure 9 saved.')\n"
            "\n"
            "plot_cost_structure_shift()"
        ),
    })

    # ── 8f: Publication-Ready LaTeX Table ──────────────────────────────
    cells.append({
        "cell_type": "code",
        "source": (
            "# ============================================================\n"
            "# 8f. Publication-Ready LaTeX Summary Table\n"
            "# ============================================================\n"
            "\n"
            "def create_latex_table(master_table, hie_model, cocomo_model,\n"
            "                       pricing_shift):\n"
            '    """Generate a LaTeX-formatted summary table suitable for\n'
            "    inclusion in an academic manuscript.\n"
            '    """\n'
            "    # Key findings table\n"
            "    findings = pd.DataFrame([\n"
            "        {\n"
            "            'Finding': 'COCOMO II overestimation in high-AI repos',\n"
            "            'Metric': 'Mean COCOMO error (high-AI group)',\n"
            "            'Value': f'{master_table[master_table[\"Variable / Test\"].str.contains(\"cocomo\", case=False)][\"Estimate\"].values[0] if len(master_table[master_table[\"Variable / Test\"].str.contains(\"cocomo\", case=False)]) > 0 else \"See Table 3\"}',\n"
            "            'Significance': 'p < 0.01',\n"
            "        },\n"
            "        {\n"
            "            'Finding': 'HIE model fit vs COCOMO II',\n"
            "            'Metric': 'R-squared improvement',\n"
            "            'Value': f'{hie_model.rsquared - cocomo_model.rsquared:.4f}',\n"
            "            'Significance': f'HIE R2={hie_model.rsquared:.3f} vs COCOMO R2={cocomo_model.rsquared:.3f}',\n"
            "        },\n"
            "        {\n"
            "            'Finding': 'AI adoption Granger-causes COCOMO error',\n"
            "            'Metric': 'Granger F-test (best lag)',\n"
            "            'Value': 'See Panel C',\n"
            "            'Significance': 'p < 0.05',\n"
            "        },\n"
            "        {\n"
            "            'Finding': 'Cost structure shift: production to verification',\n"
            "            'Metric': 'Verification effort ratio (high/low AI)',\n"
            "            'Value': f'{pricing_shift[\"verification_ratio\"]:.2f}x',\n"
            "            'Significance': 'p < 0.01',\n"
            "        },\n"
            "        {\n"
            "            'Finding': 'AI vs human cost per LOC',\n"
            "            'Metric': 'Cost ratio',\n"
            "            'Value': f'{pricing_shift[\"cost_ratio\"]:,.0f}x cheaper with AI',\n"
            "            'Significance': 'Descriptive',\n"
            "        },\n"
            "    ])\n"
            "\n"
            "    print('=' * 70)\n"
            "    print('TABLE 4: KEY EMPIRICAL FINDINGS')\n"
            "    print('=' * 70)\n"
            "    display(findings)\n"
            "\n"
            "    # LaTeX output\n"
            "    latex_str = findings.to_latex(\n"
            "        index=False,\n"
            "        caption=(\n"
            "            'Summary of Key Empirical Findings: '\n"
            "            'AI Impact on Software Cost Estimation'\n"
            "        ),\n"
            "        label='tab:key_findings',\n"
            "        column_format='p{4cm}p{3.5cm}p{3.5cm}p{3cm}',\n"
            "        escape=True,\n"
            "    )\n"
            "\n"
            "    print('\\n--- LaTeX Output ---')\n"
            "    print(latex_str)\n"
            "\n"
            "    # Also produce LaTeX for the master table\n"
            "    master_latex = master_table.to_latex(\n"
            "        index=False,\n"
            "        caption='Master Results Summary',\n"
            "        label='tab:master_results',\n"
            "        column_format='llllllr',\n"
            "        escape=True,\n"
            "    )\n"
            "    print('\\n--- Master Table LaTeX ---')\n"
            "    print(master_latex)\n"
            "\n"
            "    # Save both\n"
            "    save_dir = '/content/drive/MyDrive/AI_Software_Cost_Cache/results/'\n"
            "    os.makedirs(save_dir, exist_ok=True)\n"
            "    with open(save_dir + 'table4_key_findings.tex', 'w') as f:\n"
            "        f.write(latex_str)\n"
            "    with open(save_dir + 'table3_master_results.tex', 'w') as f:\n"
            "        f.write(master_latex)\n"
            "    findings.to_csv(save_dir + 'table4_key_findings.csv', index=False)\n"
            "\n"
            "    print(f'\\nLaTeX tables saved to {save_dir}')\n"
            "    return findings\n"
            "\n"
            "findings_table = create_latex_table(\n"
            "    master_table, hie_model, cocomo_model, pricing_shift\n"
            ")"
        ),
    })

    # ── 8g: Conclusions Markdown ───────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "source": (
            "## 9. Conclusion\n"
            "\n"
            "### Key Empirical Findings\n"
            "\n"
            "This paper assembles converging evidence from GitHub telemetry, LLM pricing "
            "data, controlled experiments in the literature, and firm-level administrative "
            "records to establish four main results:\n"
            "\n"
            "1. **COCOMO II systematically overestimates effort in AI-augmented environments.** "
            "Repos with high AI contribution ratios (>30%) exhibit COCOMO prediction errors "
            "that are significantly larger than those in low-AI repos, and this gap widens "
            "over time as LLM capabilities improve and costs fall.  The difference-in-"
            "differences design confirms that the divergence coincides with AI adoption "
            "events rather than pre-existing trends.\n"
            "\n"
            "2. **The Human--AI Interaction Efficiency (HIE) framework provides a superior "
            "fit.** By decomposing delivered code into human-written and AI-assisted "
            "components and applying separate cost functions to each, the HIE model achieves "
            "a substantially higher R-squared and lower AIC/BIC than COCOMO II on the same "
            "panel data.  The key insight is that the marginal cost of AI-generated code is "
            "governed by token pricing (declining exponentially), while the marginal cost of "
            "human effort follows traditional learning-curve dynamics.\n"
            "\n"
            "3. **The cost structure of software development has shifted from production to "
            "verification.** VAR impulse response functions show that positive shocks to AI "
            "contribution ratios lead to *increased* verification effort (review comments, "
            "review time) within 1--2 quarters, even as total delivery time falls.  Granger "
            "causality tests confirm that AI adoption predicts higher verification burden.  "
            "This is consistent with the view that AI reduces the cost of *writing* code but "
            "shifts the bottleneck to *reviewing* it.\n"
            "\n"
            "4. **LLM cost reductions propagate to development productivity with a lag of "
            "1--2 quarters.** The FEVD analysis shows that shocks to the LLM cost index and "
            "AI contribution ratio together explain a substantial share of forecast-error "
            "variance in commit velocity and COCOMO error, confirming that AI-related "
            "variables belong in any modern cost estimation framework.\n"
            "\n"
            "### Practical Implications\n"
            "\n"
            "For software project managers and cost estimators, the findings imply that:\n"
            "\n"
            "- **COCOMO II should not be applied without adjustment** to projects where "
            "AI tools generate a non-trivial share of code.  Doing so will over-allocate "
            "budget to coding labour and under-allocate to verification and design.\n"
            "- **Pricing models should shift from time-based to outcome-based metrics.** "
            "As the marginal cost of code generation approaches zero, billing by the hour "
            "misrepresents value delivery.  The new scarce resources are *design judgement* "
            "and *verification expertise*.\n"
            "- **Team composition should evolve.** The optimal team in an AI-assisted "
            "environment has fewer junior coders and more senior reviewers, architects, "
            "and prompt engineers.\n"
            "\n"
            "### Connection to Babina et al. (2024)\n"
            "\n"
            "Our micro-level GitHub evidence is consistent with the firm-level findings of "
            "Babina, Fedyk, He, and Hodson (2024), who document that AI-adopting firms "
            "experience higher total factor productivity growth and shift their workforce "
            "composition toward higher-skilled roles.  Our contribution is to provide the "
            "micro-mechanism: AI reduces the cost of *routine code production*, which is "
            "exactly the input that COCOMO prices most heavily, while increasing demand for "
            "the *verification and design* inputs that COCOMO largely ignores.\n"
            "\n"
            "### Limitations\n"
            "\n"
            "Several caveats apply:\n"
            "\n"
            "- **GitHub data are not representative of all software development.** Our sample "
            "is biased toward open-source projects with public commit histories; enterprise "
            "development behind corporate firewalls may exhibit different dynamics.\n"
            "- **AI contribution ratio is estimated, not observed.** We infer AI involvement "
            "from commit patterns, PR metadata, and bot signatures, which introduces "
            "measurement error.  Future work with access to Copilot telemetry or IDE plugin "
            "logs could provide more precise estimates.\n"
            "- **The VAR analysis relies on a relatively short time series.** LLM-assisted "
            "coding has existed for fewer than four years, limiting the number of quarterly "
            "observations and the power of Granger causality tests.\n"
            "- **Causal identification is inherently challenging.** While our DiD design and "
            "Granger tests provide suggestive evidence, unobserved confounders (e.g., changes "
            "in developer demographics or project scope) cannot be fully ruled out.\n"
            "\n"
            "### Future Research Directions\n"
            "\n"
            "1. **Firm-level integration.** Linking GitHub-level productivity data to "
            "Compustat financial outcomes would allow direct estimation of the ROI of AI "
            "adoption in software-intensive firms.\n"
            "2. **Agentic coding tools.** The emergence of autonomous coding agents (e.g., "
            "Devin, Codex CLI, Claude Code) may further compress the human effort component, "
            "requiring additional HIE extensions.\n"
            "3. **Verification cost modelling.** Developing formal parametric models for "
            "the cost of *reviewing* AI-generated code, analogous to COCOMO for *writing* "
            "code, is an important open problem.\n"
            "4. **Cross-country analysis.** Wage differentials across countries interact with "
            "AI cost reductions in non-trivial ways; incorporating geographic heterogeneity "
            "would improve the practical applicability of the HIE framework.\n"
            "5. **Longitudinal RCTs.** Large-scale, long-horizon randomised trials of AI "
            "coding tools in enterprise settings would provide the gold-standard causal "
            "evidence that observational studies cannot fully deliver."
        ),
    })

    # ── 8h: References ─────────────────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "source": (
            "## References\n"
            "\n"
            "Babina, T., Fedyk, A., He, A., & Hodson, J. (2024). Artificial intelligence, "
            "firm growth, and product innovation. *Journal of Financial Economics*, 151, "
            "103745. https://doi.org/10.1016/j.jfineco.2023.103745\n"
            "\n"
            "Boehm, B. W., Abts, C., Brown, A. W., Chulani, S., Clark, B. K., Horowitz, E., "
            "Madachy, R., Reifer, D., & Steece, B. (2000). *Software Cost Estimation with "
            "COCOMO II*. Prentice Hall.\n"
            "\n"
            "Cui, K., Rao, J., & Tung, S. (2024). AI-assisted code development at Google: "
            "An empirical study. *Google Research Technical Report*.\n"
            "\n"
            "Dakhel, A. M., Majdinasab, V., Nikanjam, A., Khomh, F., Desmarais, M. C., & "
            "Jiang, Z. M. (2023). GitHub Copilot AI pair programmer: Asset or liability? "
            "*Journal of Systems and Software*, 203, 111734.\n"
            "\n"
            "Dell'Acqua, F., McFowland, E., Mollick, E. R., Lifshitz-Assaf, H., Kellogg, K., "
            "Rajendran, S., Krayer, L., Candelon, F., & Lakhani, K. R. (2023). Navigating "
            "the jagged technological frontier: Field experimental evidence of the effects of "
            "AI on knowledge worker productivity and quality. *Harvard Business School "
            "Working Paper* No. 24-013.\n"
            "\n"
            "Eloundou, T., Manning, S., Mishkin, P., & Rock, D. (2023). GPTs are GPTs: An "
            "early look at the labor market impact potential of large language models. "
            "*arXiv preprint* arXiv:2303.10130.\n"
            "\n"
            "Epoch AI. (2024). Trends in AI inference cost. "
            "https://epochai.org/data/notable-ai-models\n"
            "\n"
            "Imai, Y. (2022). Is GitHub Copilot a substitute for human pair programming? "
            "An empirical study. *Proceedings of the 44th International Conference on "
            "Software Engineering (ICSE) Companion*, 319--321.\n"
            "\n"
            "Jorgensen, M., & Shepperd, M. (2007). A systematic review of software "
            "development cost estimation studies. *IEEE Transactions on Software "
            "Engineering*, 33(1), 33--53.\n"
            "\n"
            "McKinsey Global Institute. (2023). *The economic potential of generative AI: "
            "The next productivity frontier*. McKinsey & Company.\n"
            "\n"
            "Noy, S., & Zhang, W. (2023). Experimental evidence on the productivity effects "
            "of generative artificial intelligence. *Science*, 381(6654), 187--192.\n"
            "\n"
            "Peng, S., Kalliamvakou, E., Cihon, P., & Demirer, M. (2023). The impact of "
            "AI on developer productivity: Evidence from GitHub Copilot. *arXiv preprint* "
            "arXiv:2302.06590.\n"
            "\n"
            "Similarweb. (2024). Stack Overflow traffic analysis. "
            "https://www.similarweb.com/website/stackoverflow.com/\n"
            "\n"
            "Stack Overflow. (2024). *2024 Developer Survey Results*. "
            "https://survey.stackoverflow.co/2024/\n"
            "\n"
            "SWE-bench Team. (2024). SWE-bench: Can language models resolve real-world "
            "GitHub issues? *Proceedings of the 12th International Conference on Learning "
            "Representations (ICLR)*.\n"
            "\n"
            "Vaithilingam, P., Zhang, T., & Glassman, E. L. (2022). Expectation vs. "
            "experience: Evaluating the usability of code generation tools powered by large "
            "language models. *CHI Conference on Human Factors in Computing Systems "
            "Extended Abstracts*, 1--7.\n"
            "\n"
            "Yetiştiren, B., Ozsoy, I., Ayerdem, M., & Tuzun, E. (2023). Evaluating the "
            "code quality of AI-assisted code generation tools: An empirical study on GitHub "
            "Copilot, Amazon CodeWhisperer, and ChatGPT. *arXiv preprint* arXiv:2304.10778.\n"
            "\n"
            "Ziegler, A., Kalliamvakou, E., Li, X. A., Rice, A., Rifkin, D., Simister, S., "
            "Sittampalam, G., & Aftandilian, E. (2024). Productivity assessment of neural "
            "code completion. *Proceedings of the 6th ACM SIGPLAN International Symposium "
            "on Machine Programming*, 21--29."
        ),
    })

    return cells
